<a href="https://colab.research.google.com/github/pranjal1005/summer-internship-projects/blob/main/trainingday12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
type(numpy.arange(7) )


numpy.ndarray

In [ ]:
import numpy as np
arr1= np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [ ]:
arr1=np.array ( [ [1,2],[3,4],[5,6] ])
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

6
(3, 2)
int64


In [ ]:
arr2=np.arange(3)
print(arr2.shape)


(3,)


In [ ]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr1=np.arange(9)
arr1.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
import numpy as np
a = np.array([[1,2] , [3,4] ])
print(a)


[[1 2]
 [3 4]]


In [ ]:
b=a.transpose()
print(b)

[[1 3]
 [2 4]]


In [ ]:
import numpy as np
a = np.array([[1,2] , [3,4], [4,5] ])
print(a)

[[1 2]
 [3 4]
 [4 5]]


In [ ]:
import pandas
pandas.Series( [10,2,34,4] )

0    10
1     2
2    34
3     4
dtype: int64

In [ ]:
import pandas
series1= pandas.Series( [10,2,34,4] )
series1.values

array([10,  2, 34,  4])

In [ ]:
series1.index
print(series1.index)

series1.values
print(series1[0])

RangeIndex(start=0, stop=4, step=1)
10


In [ ]:
import pandas
series1= pandas.Series( [10,2,34,4] )
series1[0]= 90 #update
series1[5]= 1000

series1.max()
series1.idxmin()

np.int64(1)

In [ ]:
series1

0      90
1       2
2      34
3       4
5    1000
dtype: int64

In [ ]:
import pandas as pd
series1 = pd.Series([10,2,34,4], index=["A", "B","C", "D"] )#series with customize index
series1.to_dict()

{'A': 10, 'B': 2, 'C': 34, 'D': 4}

In [ ]:
arr1=np.array([10,13,15] )
series1 =pd.Series(arr1)
series1.is_unique

True

In [ ]:
series1.nunique() # total unique elemenet

3

In [ ]:
arr1=np.array([100,13,15,10,15,90] )
series1= pd.Series(arr1)
series1.drop_duplicates(inplace=True)

In [ ]:
series1

0    100
1     13
2     15
3     10
5     90
dtype: int64

In [ ]:
person = {"name": "pranjal","age ": 25,"city": "Jaipurrr"}
print(person["name"])
person["age"] = 19
person["country"]="India"
print(person)

pranjal
{'name': 'pranjal', 'age ': 25, 'city': 'Jaipurrr', 'age': 19, 'country': 'India'}


In [ ]:
dictionary1 = {10:"abc", 12:"def"}
dictionary1= {10:"abc", 12:"def"}
dictionary1[10]
pd.Series(dictionary1)

10    abc
12    def
dtype: object

In [ ]:
data = [[10,12,13], [13,14,15] ]
pd.DataFrame(data)

0   1   2
0  10  12  13
1  13  14  15

In [ ]:
data = [[10,12,13], [13,14,15] ]
df = pd.DataFrame(data, columns=["Product1","Product2","Product3"])

In [ ]:
type(df ["Product1"] )

pandas.core.series.Series

In [ ]:
import pandas as pd

df = pd.read_csv('movies.csv')
print(df)


      movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                  

In [ ]:
import pandas as pd

df = pd.read_csv('links.csv')
print(df)

      movieId   imdbId    tmdbId
0           1   114709     862.0
1           2   113497    8844.0
2           3   113228   15602.0
3           4   114885   31357.0
4           5   113041   11862.0
...       ...      ...       ...
9737   193581  5476944  432131.0
9738   193583  5914996  445030.0
9739   193585  6397426  479308.0
9740   193587  8391976  483455.0
9741   193609   101726   37891.0

[9742 rows x 3 columns]


In [ ]:
import pandas as pd

df = pd.read_csv('ratings.csv')
print(df)

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]


In [ ]:
import pandas as pd

df = pd.read_csv('tags.csv')
print(df)

      userId  movieId               tag   timestamp
0          2    60756             funny  1445714994
1          2    60756   Highly quotable  1445714996
2          2    60756      will ferrell  1445714992
3          2    89774      Boxing story  1445715207
4          2    89774               MMA  1445715200
...      ...      ...               ...         ...
3678     606     7382         for katie  1171234019
3679     606     7936           austere  1173392334
3680     610     3265            gun fu  1493843984
3681     610     3265  heroic bloodshed  1493843978
3682     610   168248  Heroic Bloodshed  1493844270

[3683 rows x 4 columns]


In [ ]:
import pandas as pd

df = pd.read_csv('movies.csv')


In [ ]:
df.columns

Index(['movieId', 'title', 'genres'], dtype='object')

In [ ]:
value_counts1 = df['title'].value_counts()
print(value_counts1)


title
Emma (1996)                                            2
War of the Worlds (2005)                               2
Eros (2004)                                            2
Confessions of a Dangerous Mind (2002)                 2
Saturn 3 (1980)                                        2
                                                      ..
Rape Me (Baise-moi) (2000)                             1
Alice (1990)                                           1
Another Woman (1988)                                   1
Beach Blanket Bingo (1965)                             1
Crimson Rivers, The (Rivières pourpres, Les) (2000)    1
Name: count, Length: 9737, dtype: int64


In [ ]:
top_3 = df['title'].value_counts().head(3)
print("Top 3 titles based on count: ")
print(top_3)


Top 3 titles based on count: 
title
Emma (1996)                 2
War of the Worlds (2005)    2
Eros (2004)                 2
Name: count, dtype: int64


In [ ]:
unique_values1 = df['title'].unique()
print("Unique values:")
print(unique_values1)


Unique values:
['Toy Story (1995)' 'Jumanji (1995)' 'Grumpier Old Men (1995)' ...
 'Flint (2017)' 'Bungo Stray Dogs: Dead Apple (2018)'
 'Andrew Dice Clay: Dice Rules (1991)']


In [ ]:
df_no_duplicates = df.drop_duplicates(subset='title')
print(df_no_duplicates)


      movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                  

In [ ]:
df['movieId'] = df['movieId'].astype(float)
print(df.dtypes)


movieId    float64
title       object
genres      object
dtype: object
